const json = (payload: Record<string, unknown>) => JSON.stringify(payload, null, 2);

export const pricingPrompts = {
  refreshDueTargets: (payload: Record<string, unknown>): string => [
    "## タスク: 期限切れターゲットの価格更新",
    "",
    "24時間以上スナップショットが更新されていない全ターゲットに対して、",
    "job_queue に pricing.recomputeSnapshot ジョブを投入してください。",
    "",
    "### 手順:",
    "1. DB から全アクティブターゲットを取得し、各ターゲットの最新スナップショットを確認する",
    "2. 24h以上経過したターゲットに対して job_queue に INSERT する:",
    '   INSERT INTO job_queue (id, job_type, status, payload) VALUES',
    "   (gen_random_uuid(), 'pricing.recomputeSnapshot', 'pending',",
    "    '{\"targetId\": \"...\"}');",
    "3. 投入したジョブ数を報告する",
    "",
    `ペイロード: ${json(payload)}`,
  ].join("\n"),

  recomputeSnapshot: (payload: Record<string, unknown>): string => [
    "## タスク: 価格スナップショット再計算",
    "",
    `targetId: ${payload.targetId} の実売データからスナップショットを算出し保存する。`,
    "",
    "### ステップ1: 実売データ取得",
    `以下を実行: npx tsx apps/runner/src/scripts/fetch-mercari.ts ${payload.targetId}`,
    "",
    "### ステップ2: 商品分類",
    "ステップ1の出力JSONのitems配列から、各商品を include/exclude に分類せよ。",
    "",
    "**include の条件:**",
    "- 対象製品の本体そのものの成約データ",
    "- 標準付属品（純正充電ケーブル、箱等）付きは許容",
    "",
    "**exclude の条件:**",
    "- ソフト単体、周辺機器、部品、ジャンク/故障品",
    "- 箱のみ、説明書のみ、ケース・カバー・フィルムのみ",
    "- 複数台セット、まとめ売り（本体単価が不明）",
    "- 別機種、互換アクセサリ",
    "- 不確実な場合は exclude",
    "",
    "### ステップ3: 価格計算",
    "include の商品の price(円) から以下を計算:",
    "1. sellEstimateYen = 10%トリム中央値",
    "   - 昇順ソート → floor(件数×0.1) 件を上下から除去 → 残りの中央値",
    "2. buyLimitYen = max(0, round(sellEstimateYen × (1 - 0.15 - 0.10) - 850))",
    "3. soldCount30d = updated が過去30日以内の商品数",
    "4. avgDaysToSell = 各商品の (updated - created) 日数の平均（120日超は除外）",
    "5. liquidityScore = max(0, min(100, round(min(60, soldCount30d×3) + 40 - min(40, avgDaysToSell×2))))",
    "",
    "**include が 5件未満の場合はジョブを失敗させよ（合成データは生成しない）。**",
    "",
    "### ステップ4: DB保存",
    "以下を実行:",
    `echo '<JSON>' | npx tsx apps/runner/src/scripts/save-snapshot.ts`,
    "",
    "JSON形式:",
    '{"targetId":"...","sellEstimateYen":N,"buyLimitYen":N,"liquidityScore":N,',
    ' "metadata":{"source":"runner.pricing.claude-v1","sampleCount":N,"keyword":"..."}}',
    "",
    "### 結果フォーマット:",
    "```json",
    '{"status":"success","targetId":"...","sellEstimateYen":N,"buyLimitYen":N,"sampleCount":N}',
    "```",
  ].join("\n"),

  probeMercari: (payload: Record<string, unknown>): string => [
    "## タスク: メルカリ実売データ探索",
    "",
    "メルカリの検索APIを使って実売データを取得してください。",
    "",
    "### 手順:",
    `npx tsx apps/runner/src/scripts/fetch-mercari.ts ${payload.targetId ?? "target_switch_lite"}`,
    "",
    "結果を分析し、商品の価格帯、状態分布を報告してください。",
    "",
    `ペイロード: ${json(payload)}`,
  ].join("\n"),

  backfillSnapshots: (payload: Record<string, unknown>): string => [
    "## タスク: 過去スナップショットのバックフィル",
    "",
    "全アクティブターゲットに対して pricing.recomputeSnapshot ジョブを投入してください。",
    "",
    `ペイロード: ${json(payload)}`,
  ].join("\n"),
};
