const json = (payload: Record<string, unknown>) => JSON.stringify(payload, null, 2);

export const targetsPrompts = {
  optimize: (payload: Record<string, unknown>): string => [
    "## タスク: ターゲット商品の最適化",
    "",
    "メルカリで利益が出る中古商品を調査し、targets テーブルを更新せよ。",
    "",
    "### 目標",
    "- 40-50件のアクティブターゲットを維持する",
    "- 1件あたり利益5,000円以上が見込める商品を優先する",
    "- 単価3万円以上、メルカリでの取引量が多い商品を選定する",
    "",
    "### 調査手順",
    "1. 現在のターゲットとスナップショットをDBから確認する",
    "   SELECT t.id, t.sku, t.title_keyword, t.is_active, s.sell_estimate_yen, s.buy_limit_yen, s.liquidity_score",
    "   FROM targets t LEFT JOIN price_snapshots s ON t.id = s.target_id",
    "   ORDER BY s.observed_at DESC;",
    "",
    "2. 利益率が低い/取引量が少ないターゲットを特定する",
    "3. Web検索で以下を調査する:",
    "   - メルカリで高く売れる中古商品カテゴリ",
    "   - 各商品の中古相場（メルカリ実売価格）",
    "   - 価格差が出やすい商品の特徴",
    "",
    "### 有望な商品カテゴリ（優先度順）",
    "1. **iPhone** 全世代（Pro/Pro Max優先、高単価）",
    "2. **MacBook** Air/Pro（非常に高単価: 8-25万）",
    "3. **iPad** Pro/Air/mini（高単価: 3-13万）",
    "4. **ゲーム機** 限定版・新型（Switch, PS5）",
    "5. **カメラ・レンズ** Sony α, Canon（超高単価: 3-30万）",
    "6. **ヘッドホン** Sony WH/WF, AirPods Max/Pro",
    "7. **その他** トレンド商品、限定コラボ品",
    "",
    "### ターゲット登録ルール",
    "各ターゲットには以下が必要:",
    "- id: スネークケースの一意ID（例: target_iphone15_pro_max_256）",
    "- sku: 大文字ハイフン区切り（例: IPHONE-15-PRO-MAX-256）",
    "- title_keyword: メルカリ通知のタイトルマッチング用（例: iPhone 15 Pro Max）",
    "- model_keyword: 型番マッチング用（オプション）",
    "- search_keyword_a: メルカリ検索キーワード主パターン（例: iphone 15 pro max 256gb simフリー 本体）",
    "- search_keyword_b: 検索キーワード副パターン（例: iphone15promax 256gb）",
    "",
    "### 更新手順",
    "1. 不採算ターゲット:",
    "   UPDATE targets SET is_active = false WHERE id = '...';",
    "2. 新規ターゲット:",
    "   INSERT INTO targets (id, sku, title_keyword, model_keyword, search_keyword_a, search_keyword_b, is_active)",
    "   VALUES ('...', '...', '...', NULL, '...', '...', true)",
    "   ON CONFLICT (sku) DO UPDATE SET title_keyword = EXCLUDED.title_keyword,",
    "   search_keyword_a = EXCLUDED.search_keyword_a, search_keyword_b = EXCLUDED.search_keyword_b,",
    "   is_active = true;",
    "3. 各新規ターゲットに対して job_queue に pricing.recomputeSnapshot を投入:",
    "   INSERT INTO job_queue (id, job_type, status, payload)",
    "   VALUES (gen_random_uuid(), 'pricing.recomputeSnapshot', 'pending', '{\"targetId\": \"...\"}');",
    "",
    "### 結果フォーマット",
    "```json",
    '{"status":"success","added":N,"deactivated":N,"totalActive":N,"targets":[...]}',
    "```",
    "",
    `ペイロード: ${json(payload)}`,
  ].join("\n"),
};
